Errors
Search:
Time    Error Host  Error Port  Error
2017-11-30T23:01:41.000Z    ip-172-31-11-189.us-east-2.compute.internal 6701    java.lang.RuntimeException: org.apache.storm.multilang.NoOutputException: Pipe to subprocess seems to be broken! No output read. Serializer Exception: Traceback (most recent call last): File "bolt.py", line 19, in <module> conn_db = boto.dynamodb2.connect_to_region(REGION, NameError: name 'REGION' is not defined at org.apache.storm.utils.ShellProcess.launch(ShellProcess.java:96) at org.apache.storm.task.ShellBolt.prepare(ShellBolt.java:150) at org.apache.storm.daemon.executor$fn__9635$fn__9648.invoke(executor.clj:794) at org.apache.storm.util$async_loop$fn__557.invoke(util.clj:482) at clojure.lang.AFn.run(AFn.java:22) at java.lang.Thread.run(Thread.java:745)
2017-11-30T23:01:41.000Z    ip-172-31-11-189.us-east-2.compute.internal 6701    java.lang.RuntimeException: org.apache.storm.multilang.NoOutputException: Pipe to subprocess seems to be broken! No output read. Serializer Exception: Traceback (most recent call last): File "bolt.py", line 19, in <module> conn_db = boto.dynamodb2.connect_to_region(REGION, NameError: name 'REGION' is not defined at org.apache.storm.utils.ShellProcess.launch(ShellProcess.java:96) at org.apache.storm.task.ShellBolt.prepare(ShellBolt.java:150) at org.apache.storm.daemon.executor$fn__9635$fn__9648.invoke(executor.clj:794) at org.apache.storm.util$async_loop$fn__557.invoke(util.clj:482) at clojure.lang.AFn.run(AFn.java:22) at java.lang.Thread.run(Thread.java:745)
2017-11-30T23:01:51.000Z    ip-172-31-11-189.us-east-2.compute.internal 6701    java.lang.RuntimeException: org.apache.storm.multilang.NoOutputException: Pipe to subprocess seems to be broken! No output read. Serializer Exception: Traceback (most recent call last): File "bolt.py", line 19, in <module> conn_db = boto.dynamodb2.connect_to_region(REGION, NameError: name 'REGION' is not defined at org.apache.storm.utils.ShellProcess.launch(ShellProcess.java:96) at org.apache.storm.task.ShellBolt.prepare(ShellBolt.java:150) at org.apache.storm.daemon.executor$fn__9635$fn__9648.invoke(executor.clj:794) at org.apache.storm.util$async_loop$fn__557.invoke(util.clj:482) at clojure.lang.AFn.run(AFn.java:22) at java.lang.Thread.run(Thread.java:745)
2017-11-30T23:01:51.000Z    ip-172-31-11-189.us-east-2.compute.internal 6701    java.lang.RuntimeException: org.apache.storm.multilang.NoOutputException: Pipe to subprocess seems to be broken! No output read. Serializer Exception: Traceback (most recent call last): File "bolt.py", line 19, in <module> conn_db = boto.dynamodb2.connect_to_region(REGION, NameError: name 'REGION' is not defined at org.apache.storm.utils.ShellProcess.launch(ShellProcess.java:96) at org.apache.storm.task.ShellBolt.prepare(ShellBolt.java:150) at org.apache.storm.daemon.executor$fn__9635$fn__9648.invoke(executor.clj:794) at org.apache.storm.util$async_loop$fn__557.invoke(util.clj:482) at clojure.lang.AFn.run(AFn.java:22) at java.lang.Thread.run(Thread.java:745)
2017-11-30T23:01:51.000Z    ip-172-31-11-189.us-east-2.compute.internal 6700    java.lang.RuntimeException: org.apache.storm.multilang.NoOutputException: Pipe to subprocess seems to be broken! No output read. Serializer Exception: Traceback (most recent call last): File "bolt.py", line 19, in <module> conn_db = boto.dynamodb2.connect_to_region(REGION, NameError: name 'REGION' is not defined at org.apache.storm.utils.ShellProcess.launch(ShellProcess.java:96) at org.apache.storm.task.ShellBolt.prepare(ShellBolt.java:150) at org.apache.storm.daemon.executor$fn__9635$fn__9648.invoke(executor.clj:794) at org.apache.storm.util$async_loop$fn__557.invoke(util.clj:482) at clojure.lang.AFn.run(AFn.java:22) at java.lang.Thread.run(Thread.java:745)
2017-11-30T23:01:51.000Z    ip-172-31-11-189.us-east-2.compute.internal 6700    java.lang.RuntimeException: org.apache.storm.multilang.NoOutputException: Pipe to subprocess seems to be broken! No output read. Serializer Exception: Traceback (most recent call last): File "bolt.py", line 19, in <module> conn_db = boto.dynamodb2.connect_to_region(REGION, NameError: name 'REGION' is not defined at org.apache.storm.utils.ShellProcess.launch(ShellProcess.java:96) at org.apache.storm.task.ShellBolt.prepare(ShellBolt.java:150) at org.apache.storm.daemon.executor$fn__9635$fn__9648.invoke(executor.clj:794) at org.apache.storm.util$async_loop$fn__557.invoke(util.clj:482) at clojure.lang.AFn.run(AFn.java:22) at java.lang.Thread.run(Thread.java:745)
2017-11-30T23:01:51.000Z    ip-172-31-11-189.us-east-2.compute.internal 6701    java.lang.RuntimeException: org.apache.storm.multilang.NoOutputException: Pipe to subprocess seems to be broken! No output read. Serializer Exception: Traceback (most recent call last): File "bolt.py", line 19, in <module> conn_db = boto.dynamodb2.connect_to_region(REGION, NameError: name 'REGION' is not defined at org.apache.storm.utils.ShellProcess.launch(ShellProcess.java:96) at org.apache.storm.task.ShellBolt.prepare(ShellBolt.java:150) at org.apache.storm.daemon.executor$fn__9635$fn__9648.invoke(executor.clj:794) at org.apache.storm.util$async_loop$fn__557.invoke(util.clj:482) at clojure.lang.AFn.run(AFn.java:22) at java.lang.Thread.run(Thread.java:745)
2017-11-30T23:01:51.000Z    ip-172-31-11-189.us-east-2.compute.internal 6701    java.lang.RuntimeException: org.apache.storm.multilang.NoOutputException: Pipe to subprocess seems to be broken! No output read. Serializer Exception: Traceback (most recent call last): File "bolt.py", line 19, in <module> conn_db = boto.dynamodb2.connect_to_region(REGION, NameError: name 'REGION' is not defined at org.apache.storm.utils.ShellProcess.launch(ShellProcess.java:96) at org.apache.storm.task.ShellBolt.prepare(ShellBolt.java:150) at org.apache.storm.daemon.executor$fn__9635$fn__9648.invoke(executor.clj:794) at org.apache.storm.util$async_loop$fn__557.invoke(util.clj:482) at clojure.lang.AFn.run(AFn.java:22) at java.lang.Thread.run(Thread.java:745)
2017-11-30T23:01:51.000Z    ip-172-31-11-189.us-east-2.compute.internal 6700    java.lang.RuntimeException: org.apache.storm.multilang.NoOutputException: Pipe to subprocess seems to be broken! No output read. Serializer Exception: Traceback (most recent call last): File "bolt.py", line 19, in <module> conn_db = boto.dynamodb2.connect_to_region(REGION, NameError: name 'REGION' is not defined at org.apache.storm.utils.ShellProcess.launch(ShellProcess.java:96) at org.apache.storm.task.ShellBolt.prepare(ShellBolt.java:150) at org.apache.storm.daemon.executor$fn__9635$fn__9648.invoke(executor.clj:794) at org.apache.storm.util$async_loop$fn__557.invoke(util.clj:482) at clojure.lang.AFn.run(AFn.java:22) at java.lang.Thread.run(Thread.java:745)
2017-11-30T23:01:51.000Z    ip-172-31-11-189.us-east-2.compute.internal 6700    java.lang.RuntimeException: org.apache.storm.multilang.NoOutputException: Pipe to subprocess seems to be broken! No output read. Serializer Exception: Traceback (most recent call last): File "bolt.py", line 19, in <module> conn_db = boto.dynamodb2.connect_to_region(REGION, NameError: name 'REGION' is not defined at org.apache.storm.utils.ShellProcess.launch(ShellProcess.java:96) at org.apache.storm.task.ShellBolt.prepare(ShellBolt.java:150) at org.apache.storm.daemon.executor$fn__9635$fn__9648.invoke(executor.clj:794) at org.apache.storm.util$async_loop$fn__557.invoke(util.clj:482) at clojure.lang.AFn.run(AFn.java:22) at java.lang.Thread.run(Thread.java:745)